### ISSUE TITLE
Computing inner products

### ISSUE THREAD

**Issue by alphaville** [korken89/lbfgs-rs#3]
We may avoid computing more than inner products between `s` and `y` by caching `rho` (the inverse of `s'*y`).

Currently, we recompute the inner products as follows:

```rust
for (s_k, (y_k, rho_k)) in active_s.iter().zip(active_y.iter().zip(rho.iter_mut())) {
    let r = 1.0 / vec_ops::inner_product(s_k, y_k); // <-- HERE, WE RECOMPUTE s'*y

    if !r.is_finite() {
        return;
    }

    *rho_k = r
}
```
Instead, we can rotate the buffer of `rho` when appropriate.

**Comment by korken89** [comment]
Indeed, if the L-BFGS checks and C-BFGS checks passes we already have the inner product available. Good catch!

Fixed in 7f787a91d941192dd40422da13ea1e534de8a755 and similar fix in c1be7ab
