### ISSUE TITLE
Add method to clear the buffers

### ISSUE THREAD

**Issue by alphaville** [korken89/lbfgs-rs#4]
We should add a method to empty the buffers. This is often necessary: for example, in PANOC, whenever we update `gamma`, the collected pairs `(s,y)` become invalid.

**Comment by korken89** [comment]
No problem, I can add this

**Comment by alphaville** [comment]
I added a method; it should work, but we'd rather test.

**Comment by korken89** [comment]
Indeed, but it is a correct reset. Nothing more should be needed.
